version: "2.4"
# dockerfiles for each distro are in subdir ./docker named after the distro (e.g. ./docker/centos)
services:
  benchmark_io:
    container_name: "${OS_DISTRO}_benchmark_io"
    build:
      context: "."
      dockerfile: "./docker/${OS_DISTRO}/Dockerfile"
    image: "${OS_DISTRO}_benchmark_io"
    environment:
      # env vars that are passed as args to the benchmark script
      - work_dir=/tmp/sysbench
      - file_size=150
      - time=3
      - delay=1
      - TERM=xterm-256color
  shellcheck:
    container_name: shellcheck_benchmark_io
    image: koalaman/shellcheck
    volumes:
      - ./scripts:/mnt
    command: "benchmark_io"
